### ISSUE TITLE
Whats the point of this thing ? and how to use

### ISSUE THREAD

**Issue by Tr3yWay996** [redstone59/BackshotRoulette#2]
I just look the last prob thing and i do what it tells me, seems like thats how to use it but i have to rerun it each times tho so idk if its normal anyway, fun if u wanna follow what the script is telling

**Comment by redstone59** [comment]
In it's current form, Backshot Roulette does not update itself automatically.

I have been considering making a mod for Buckshot Roulette in order to have the bot play or evaluate the moves the player has done, however with the new version coming out soon, I have decided to hold off until then.

The bot's goal is to find the best position in any game of Buckshot Roulette. It uses the same strategies that a chess bot uses to evaluate the best positions (exhaustively searching every possible move, minimax and alpha-beta pruning). A good resource if you want to learn about those is Sebastian Lague's video on the minimax algorithm.

I'm glad you're having fun with it, there will be more updates to come, hopefully I'll get a GUI sorted so it's more user-friendly.
